name: LEL
title: Linear Error Localization
description: |
  Linear Error Localization
version: 0.0.1
wd: .
input:
  data:
    name: data
    type: url
    description: "url to csv file with data to be checked"
    required: yes
  rules:
    name: rules
    type: url
    description: 'url to text file with rules to be used in checking'
    required: yes
  rules:
    name: weights
    type: url
    description: weights for variable per row
    required: no
result:
  adapt:
    name: adapt
    type: url
    description: |
      file path where "LEL.R" will generate a csv file
    mimetype: text/csv
    filename: adapt.csv
  status:
    name: status
    type: url
    description: |
      status of each record (csv file)
    mimetype: text/csv
    filename: status.csv
command: >
  Rscript {service.servicedir}/LEL.R
  --data {job.input.data}
  --rules {job.input.rules}
  {if job.input.weights}--weights {job.input.weights}{/if}
  --adapt adapt.csv
  --status status.csv
