name: LEL
title: Linear Error Localization
description: |
  Linear Error Localization
version: 0.0.1
wd: .
input:
  data:
    name: data
    type: url
    description: "url to csv file with data to be checked"
    required: yes
  metadata:
    name: metadata
    type: url
    description: |
      url to ddi instance of structure of data
    required: no
  rules:
    name: rules
    type: url
    description: 'url to text file with rules to be used in checking'
    required: yes
  weights:
    name: weights
    type: url
    description: weights for variable per row
    required: no
result:
  type: "object"
  properties:
    adapt:
      name: adapt
      type: string
      description: |
        file path where "LEL.R" will generate a csv file
      mimetype: text/csv
      filename: adapt.csv
      value: "{job.url}/result/adapt"
    status:
      name: status
      type: string
      description: |
        status of each record (csv file)
      mimetype: text/csv
      filename: status.csv
      value: "{job.url}/result/status"
command: >
  Rscript {service.servicedir}/LEL.R
  --data {job.input.data}
  --rules {job.input.rules}
  {if job.input.weights}--weights {job.input.weights}{/if}
  --adapt adapt.csv
  --status status.csv
