swagger: 2
info:
  title: LEL API
  description: Linear Error Localization for data
  version: "0.1.0"
# the domain of the service
# host: api.uber.com
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
  - text/csv
consumes:
  - application/json
  - text/csv
paths:
  /LEL/job:
    post:
      summary: Create a LEL request
      description: Create a LEL request
      parameters:
        - name: body
          in: body
          description: |
            Create a LEL job supplying the input 
            parameters
          schema: 
            name: 
              type: string
            input:
              $ref: Input
      responses:
        200:
          description: Newly created job
          schema:
            $ref: Job
    get:
      summary: LEL jobs
      description: The Jobs endpoint returns information about all jobs that have been submitted.
      responses:
        200:
          description: List of jobs
          schema:
            type: array
            $items: Job
  /LEL/job/{id}:
    get:
      summary: Get LEL Job info
      description: Return the status and information on a LEL job.
      parameters:
        - name: id
          in: path
          description: id of job
          required: true
          type: string
      tags: 
        - LEL
      responses:  
        200:
          description: Job description
          schema:
            $ref: Job
        default:
          description: Unexpected error
          schema:
            $ref: Error
  /LEL/job/{id}/result/adapt/data:
    get:
      summary: get erronous data fields
      description: |
        Show per record, which of the fields are erronous according to the principle of Felligi-Holt.
        The csv file has the same number of rows and columns as the input.data DataSet, but contains
        true or false values.
      parameters:
        - name: id
          in: path
          description: id of job
          required: true
          type: string
      responses:
        200:
          description: csv data
          schema:
            type: file
  /LEL/job/{id}/result/adapt/schema:
    get:
      summary: Schema for adapt.data.
      description: Schema for adapt.data.
      parameters:
        - name: id
          in: path
          description: id of job
          required: true
          type: string
      responses:
        200:
          description: json table schema
          schema:
            type: file
  /LEL/job/{id}/result/status/data:
    get:
      summary: Get status per record
      description: Retrieve the processing information per record
      parameters:
        - name: id
          in: path
          description: id of job
          required: true
          type: string
      responses:
        200:
          description: csv data
          schema:
            type: file
  /LEL/job/{id}/result/status/schema:
    get:
      summary: Structure of status file.
      description: Structure of status file.
      parameters:
        - name: id
          in: path
          description: id of job
          required: true
          type: string
      responses:
        200:
          description: json table schema
          schema:
            type: file
  /LEL/job/{id}/result/log:
    get:
      summary: get logging information of job.
      description: get logging information of job.
      parameters:
        - name: id
          in: path
          description: id of job
          required: true
          type: string
      responses:
        200:
          description: text file with logging information.
          schema:
            type: file
definitions:
  Job:
    properties:
      id: 
        type: string
        required: yes 
      name:
        type: string
        required: yes
      status:
        type: string
      created:
        type: string
        format: date-time
      url:
        type: string
        format: url
      input:
        type: Input
        description: "input parameters" 
        $ref: Input
      result:
        type: Result
        $ref: Result
      started:
        type: string
        format: date-time
      ended:
        type: string
        format: date-time
  DataSet:
    properties:
      data: 
        type: file
        description: csv data file
      schema:
        type: file
        description: |
          *json table schema* describing the data structure of the *csv* data.
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Input:
    properties:
      data:
        type: DataSet
        description: Data to be checked.
        required: yes
        $ref: DataSet
      rules:
        type: string
        format: url
        description: file with linear rules
        required: yes
      weight:
        type: string
        format: url
        description: File with weights to be used in error localization. Weight must be have same structure as input.data.
        required: no
  Result:
    properties:
      adapt:
        type: DataSet
        $ref: DataSet
      status:
        type: DataSet
        $ref: DataSet
