name: LEC
title: Linear Error Correction
description: |
  Linear Error Correction
version: 0.0.1
wd: .
input:
  data:
    name: data
    type: url
    description: "url to csv file with data to be corrected"
    required: yes
  metadata:
    name: metadata
    type: url
    description: |
      url to ddi instance of structure of data
    required: no
  localization:
    name: localization
    type: url
    description: |
       url to csv with localized variables
    required: yes
  rules:
    name: rules
    type: url
    description: 'url to text file with rules to be used for correction'
    required: yes
  weights:
    name: weights
    type: url
    description: weights for variable per row
    required: no
result:
  adjusted:
    name: adjusted
    type: url
    description: |
      file path where "LEC.R" will generate a csv file
    mimetype: text/csv
    filename: adjusted.csv
command: >
  Rscript {service.servicedir}\LEC.R
  --data {job.input.data}
  --localization {job.input.localization}
  --rules {job.input.rules}
  {if job.input.weights}--weights {job.input.weights}{/if}
  --adjusted adjusted.csv