name: LRC
title: Linear Rule Checking
description: |
  Linear Rule Checking
version: 0.0.1
wd: .
input:
  data:
    name: data
    type: url
    description: "url to data to be checked"
    require: yes
  rules:
    name: rules
    type: url
    description: 'url to rules'
    required: yes
result:
  checks:
    name: checks
    type: url
    description: 
    url: '{service.url}/job/{job.id}/result/checks.csv'
command: >
  Rscript LRC.R
  --data {job.input.data}
  --rules {job.input.rules}
  --checks job/{job.id}/result/checks.csv